packages:
  - packages/*
  - apps/*
allowBuilds:
  esbuild: true
  webgpu: false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.85'
  - '@ai-sdk/provider-utils@5.0.43'
  - '@ai-sdk/provider@4.0.17'
  - ai@7.0.105
  - lucide-react@1.47.0
