import type { Schema } from '../packages/core/src/types.ts'

export interface Domain {
  name: string

  split: 'train' | 'transfer'
  schema: Schema
  people: string[]
  words: string[]
}

const v = (...names: string[]) =>
  Object.fromEntries(names.map(n => n.split('|')).map(([c, ...a]) => [c, a]))

export const DOMAINS: Domain[] = [
  {
    name: 'issues',
    split: 'train',
    schema: {
      entity: ['issue', 'ticket', 'task'],
      fields: [
        {
          name: 'status',
          kind: 'enum',
          aliases: ['state'],
          values: v('open|opened|active', 'closed|done|resolved|fixed', 'blocked|stuck'),
        },
        {
          name: 'type',
          kind: 'enum',
          aliases: ['kind'],
          values: v('bug|defect', 'feature|enhancement', 'chore'),
        },
        {
          name: 'priority',
          kind: 'enum',
          aliases: ['severity'],
          values: v('urgent|critical|p0', 'high', 'low|minor'),
        },
        { name: 'author', kind: 'person', aliases: ['from', 'by', 'reporter', 'reported'] },
        { name: 'assignee', kind: 'person', aliases: ['assigned', 'owner'] },
        {
          name: 'created',
          kind: 'date',
          aliases: ['filed'],
          adjectives: { newest: 'desc', latest: 'desc', oldest: 'asc', recent: 'desc' },
        },
        { name: 'updated', kind: 'date', aliases: ['touched'] },
        {
          name: 'comments',
          kind: 'number',
          aliases: ['replies'],
          adjectives: { busiest: 'desc', quietest: 'asc' },
        },
        {
          name: 'points',
          kind: 'number',
          aliases: ['estimate'],
          adjectives: { big: 'desc', biggest: 'desc', small: 'asc', smallest: 'asc' },
        },
        { name: 'title', kind: 'text', aliases: ['summary'] },
      ],
    },
    people: [
      'sam',
      'alice',
      'bob',
      'priya',
      'chen',
      'maria',
      'omar',
      'yuki',
      'lena',
      'diego',
      'nina',
      'raj',
      'tom',
      'zoe',
      'ivan',
    ],
    words: [
      'auth',
      'login',
      'timeout',
      'crash',
      'deploy',
      'cache',
      'webhook',
      'migration',
      'dashboard',
      'billing',
      'oauth',
      'latency',
      'onboarding',
      'sidebar',
      'upload',
    ],
  },
  {
    name: 'mail',
    split: 'train',
    schema: {
      entity: ['email', 'mail', 'message'],
      fields: [
        {
          name: 'folder',
          kind: 'enum',
          aliases: ['mailbox'],
          values: v('inbox', 'outbox', 'drafts', 'spam|junk', 'trash|deleted'),
        },
        {
          name: 'flag',
          kind: 'enum',
          aliases: ['marked'],
          values: v('unread|unseen', 'read|seen', 'starred|flagged|important'),
        },
        { name: 'sender', kind: 'person', aliases: ['from', 'by'] },
        { name: 'recipient', kind: 'person', aliases: ['cc', 'addressed'] },
        {
          name: 'received',
          kind: 'date',
          aliases: ['arrived', 'dated'],
          adjectives: { freshest: 'desc', earliest: 'asc' },
        },
        { name: 'attachments', kind: 'number', aliases: ['attached'] },
        {
          name: 'bytes',
          kind: 'number',
          aliases: ['kb'],
          adjectives: { large: 'desc', largest: 'desc', tiny: 'asc' },
        },
        { name: 'subject', kind: 'text', aliases: ['body'] },
      ],
    },
    people: [
      'hannah',
      'marcus',
      'sofia',
      'liam',
      'aisha',
      'peter',
      'ingrid',
      'carlos',
      'mei',
      'jonas',
      'fatima',
      'george',
      'elena',
      'kofi',
      'ruth',
    ],
    words: [
      'invoice',
      'receipt',
      'meeting',
      'offer',
      'contract',
      'newsletter',
      'renewal',
      'interview',
      'flight',
      'booking',
      'payroll',
      'quote',
      'webinar',
      'reminder',
      'refund',
    ],
  },
  {
    name: 'files',
    split: 'train',
    schema: {
      entity: ['file', 'document', 'doc'],
      fields: [
        {
          name: 'format',
          kind: 'enum',
          aliases: ['filetype'],
          values: v(
            'pdf',
            'image|photo|picture|png',
            'video|movie|clip',
            'spreadsheet|sheet|csv',
            'folder|directory',
          ),
        },
        {
          name: 'access',
          kind: 'enum',
          aliases: ['visibility'],
          values: v('shared|public', 'private|unshared', 'archived'),
        },
        { name: 'creator', kind: 'person', aliases: ['by', 'from', 'uploaded'] },
        { name: 'editor', kind: 'person', aliases: ['edited'] },
        {
          name: 'modified',
          kind: 'date',
          aliases: ['changed'],
          adjectives: { stalest: 'asc', hottest: 'desc' },
        },
        {
          name: 'size',
          kind: 'number',
          aliases: ['mb', 'gb'],
          adjectives: { huge: 'desc', bulkiest: 'desc', compact: 'asc' },
        },
        { name: 'views', kind: 'number', aliases: ['opens'] },
        { name: 'filename', kind: 'text', aliases: ['path'] },
      ],
    },
    people: [
      'noah',
      'emma',
      'kenji',
      'lucia',
      'abdul',
      'greta',
      'pablo',
      'mina',
      'oscar',
      'tara',
      'felix',
      'anya',
      'hugo',
      'leila',
      'bruno',
    ],
    words: [
      'budget',
      'roadmap',
      'logo',
      'proposal',
      'resume',
      'agenda',
      'handbook',
      'wireframe',
      'forecast',
      'backup',
      'slides',
      'brief',
      'mockup',
      'audit',
      'policy',
    ],
  },
  {
    name: 'commits',
    split: 'train',
    schema: {
      entity: ['commit', 'change', 'patch'],
      fields: [
        {
          name: 'branch',
          kind: 'enum',
          aliases: ['ref'],
          values: v('main|master|trunk', 'develop|dev', 'release|stable'),
        },
        {
          name: 'category',
          kind: 'enum',
          aliases: ['scope'],
          values: v(
            'fix|hotfix|bugfix',
            'feat',
            'refactor|cleanup',
            'docs|documentation',
            'test|spec',
          ),
        },
        { name: 'committer', kind: 'person', aliases: ['by', 'from', 'authored'] },
        { name: 'reviewer', kind: 'person', aliases: ['reviewed', 'approved'] },
        {
          name: 'pushed',
          kind: 'date',
          aliases: ['landed', 'merged'],
          adjectives: { freshly: 'desc', original: 'asc' },
        },
        {
          name: 'additions',
          kind: 'number',
          aliases: ['lines', 'insertions'],
          adjectives: { massive: 'desc', trivial: 'asc' },
        },
        { name: 'message', kind: 'text', aliases: ['msg', 'description'] },
      ],
    },
    people: [
      'linus',
      'grace',
      'ada',
      'dennis',
      'margaret',
      'ken',
      'barbara',
      'guido',
      'brendan',
      'anders',
      'yukihiro',
      'bjarne',
      'radia',
      'tim',
      'vint',
    ],
    words: [
      'parser',
      'typo',
      'lint',
      'bump',
      'revert',
      'flaky',
      'regression',
      'dependency',
      'config',
      'logging',
      'pipeline',
      'schema',
      'rename',
      'benchmark',
      'locale',
    ],
  },

  {
    name: 'contacts',
    split: 'transfer',
    schema: {
      entity: ['contact', 'person', 'people', 'entry'],
      fields: [
        {
          name: 'group',
          kind: 'enum',
          aliases: ['circle'],
          values: v(
            'family|relatives',
            'work|colleagues|coworkers',
            'friends|buddies',
            'vip|favorites',
          ),
        },
        {
          name: 'channel',
          kind: 'enum',
          aliases: ['platform'],
          values: v('phone|mobile|cell', 'whatsapp', 'telegram', 'linkedin'),
        },
        { name: 'introducer', kind: 'person', aliases: ['via', 'introduced', 'from'] },
        { name: 'manager', kind: 'person', aliases: ['boss', 'reports'] },
        {
          name: 'met',
          kind: 'date',
          aliases: ['added', 'birthday'],
          adjectives: { fresh: 'desc', ancient: 'asc' },
        },
        {
          name: 'calls',
          kind: 'number',
          aliases: ['conversations'],
          adjectives: { chattiest: 'desc', silent: 'asc' },
        },
        { name: 'age', kind: 'number', aliases: ['aged'] },
        { name: 'notes', kind: 'text', aliases: ['bio', 'memo'] },
      ],
    },
    people: [
      'walter',
      'beatrice',
      'tariq',
      'svetlana',
      'kwame',
      'ines',
      'hiro',
      'dalia',
      'magnus',
      'chiara',
      'arjun',
      'solveig',
      'mateo',
      'nadia',
      'desmond',
    ],
    words: [
      'tennis',
      'wedding',
      'landlord',
      'dentist',
      'plumber',
      'reunion',
      'neighbor',
      'mentor',
      'investor',
      'climbing',
      'bookclub',
      'carpool',
      'alumni',
      'vendor',
      'recruiter',
    ],
  },
  {
    name: 'music',
    split: 'transfer',
    schema: {
      entity: ['song', 'track', 'tune'],
      fields: [
        {
          name: 'genre',
          kind: 'enum',
          aliases: ['style'],
          values: v(
            'rock',
            'jazz',
            'pop',
            'techno|electronic',
            'classical|orchestral',
            'hiphop|rap',
          ),
        },
        {
          name: 'mood',
          kind: 'enum',
          aliases: ['vibe'],
          values: v('chill|mellow|calm', 'upbeat|energetic', 'sad|melancholy'),
        },
        { name: 'artist', kind: 'person', aliases: ['singer', 'band', 'performed', 'by'] },
        { name: 'producer', kind: 'person', aliases: ['produced'] },
        {
          name: 'released',
          kind: 'date',
          aliases: ['dropped', 'recorded'],
          adjectives: { modern: 'desc', vintage: 'asc' },
        },
        {
          name: 'plays',
          kind: 'number',
          aliases: ['listens', 'streams'],
          adjectives: { popular: 'desc', obscure: 'asc' },
        },
        {
          name: 'duration',
          kind: 'number',
          aliases: ['length', 'seconds'],
          adjectives: { longest: 'desc', long: 'desc', shortest: 'asc', short: 'asc' },
        },
        { name: 'lyrics', kind: 'text', aliases: ['album'] },
      ],
    },
    people: [
      'miles',
      'nico',
      'bjork',
      'fela',
      'aretha',
      'ravi',
      'celia',
      'django',
      'ella',
      'thom',
      'umm',
      'astor',
      'patti',
      'caetano',
      'sade',
    ],
    words: [
      'rain',
      'midnight',
      'ocean',
      'heartbreak',
      'summer',
      'highway',
      'dancing',
      'moonlight',
      'river',
      'goodbye',
      'fire',
      'dreams',
      'lonely',
      'sunrise',
      'thunder',
    ],
  },
  {
    name: 'recipes',
    split: 'transfer',
    schema: {
      entity: ['recipe', 'dish', 'meal'],
      fields: [
        {
          name: 'cuisine',
          kind: 'enum',
          aliases: ['origin'],
          values: v('italian', 'thai', 'mexican', 'indian', 'french'),
        },
        {
          name: 'diet',
          kind: 'enum',
          aliases: ['dietary'],
          values: v('vegan|plantbased', 'vegetarian|veggie', 'glutenfree|celiac', 'keto|lowcarb'),
        },
        { name: 'chef', kind: 'person', aliases: ['cook', 'cooked', 'by'] },
        { name: 'submitter', kind: 'person', aliases: ['submitted', 'posted'] },
        {
          name: 'published',
          kind: 'date',
          aliases: ['featured'],
          adjectives: { trending: 'desc', classic: 'asc' },
        },
        {
          name: 'calories',
          kind: 'number',
          aliases: ['kcal'],
          adjectives: { lightest: 'asc', richest: 'desc' },
        },
        {
          name: 'cooktime',
          kind: 'number',
          aliases: ['prep'],
          adjectives: { quick: 'asc', quickest: 'asc', slow: 'desc' },
        },
        { name: 'ingredients', kind: 'text', aliases: ['pantry'] },
      ],
    },
    people: [
      'julia',
      'yotam',
      'samin',
      'jacques',
      'madhur',
      'nigella',
      'massimo',
      'alice-w',
      'rene',
      'niki',
      'jiro',
      'dominique',
      'asma',
      'enrique',
      'claudia',
    ],
    words: [
      'garlic',
      'basil',
      'tofu',
      'chickpea',
      'lemon',
      'mushroom',
      'coconut',
      'ginger',
      'saffron',
      'pumpkin',
      'noodle',
      'paprika',
      'almond',
      'lentil',
      'miso',
    ],
  },
  {
    name: 'shipments',
    split: 'transfer',
    schema: {
      entity: ['shipment', 'parcel', 'package', 'delivery'],
      fields: [
        {
          name: 'stage',
          kind: 'enum',
          aliases: ['progress'],
          values: v(
            'pending|waiting',
            'transit|shipping|enroute',
            'delivered|completed',
            'returned|refunded',
            'lost|missing',
          ),
        },
        {
          name: 'carrier',
          kind: 'enum',
          aliases: ['shipper'],
          values: v('ups', 'fedex', 'dhl', 'usps'),
        },
        { name: 'courier', kind: 'person', aliases: ['driver', 'carried', 'by'] },
        { name: 'customer', kind: 'person', aliases: ['buyer', 'consignee', 'for'] },
        {
          name: 'shipped',
          kind: 'date',
          aliases: ['dispatched', 'eta'],
          adjectives: { soonest: 'asc', overdue: 'asc' },
        },
        {
          name: 'weight',
          kind: 'number',
          aliases: ['kg', 'grams'],
          adjectives: { heavy: 'desc', heaviest: 'desc', light: 'asc' },
        },
        {
          name: 'cost',
          kind: 'number',
          aliases: ['price', 'fee'],
          adjectives: { cheapest: 'asc', priciest: 'desc', expensive: 'desc' },
        },
        { name: 'address', kind: 'text', aliases: ['destination', 'city'] },
      ],
    },
    people: [
      'gustav',
      'amara',
      'pedro',
      'yara',
      'sven',
      'thandi',
      'luca',
      'mirela',
      'anton',
      'keiko',
      'rashid',
      'paloma',
      'viktor',
      'esme',
      'jamal',
    ],
    words: [
      'berlin',
      'fragile',
      'warehouse',
      'customs',
      'pallet',
      'lisbon',
      'oversized',
      'signature',
      'depot',
      'rotterdam',
      'perishable',
      'tariff',
      'dock',
      'osaka',
      'locker',
    ],
  },
]
